### PR TITLE
keylayout: remove camera button key mapping

### PR DESCRIPTION
**Pull request by alviteri**
Signed-off-by: David Viteri <davidteri91@gmail.com>

### CODE REVIEW

**Comment by mlehtima** [comment]
Wouldn't it make sense to also remove the focus key mapping?

**Comment by MarijnS95** [comment]
@alviteri Would you mind explaining in the commit message _why_ this mapping has to be removed? Helps us in the future when checking the history :grin:

**Comment by alviteri** [comment]
The faking device has not cam button lol it's easy

**Comment by MarijnS95** [comment]
Well some people might not know (those who do not own this device but accidentally wtumble upon it).
While it's not too bad here, I just hope for this project to _not_ turn into an undocumented mess (like other aosp-based projects...). Commit descriptions are part of the solution.

**Comment by alviteri** [comment]
updated

**Pull request merged**
